void playerup(void);
void playerdown(void);
void* initbullet(void);
void* nextusablebullet(bullet_t *bullet);
void* nextbullet(bullet_t *bullet);
void freebullets(bullet_t *bullet);
void firebullet(bullet_t *bullet);
void inertia(bullet_t *bullet);
void bulletedgedetect(bullet_t *bullet);
void playerright(void);
void playerleft(void);
