void playerup(void);
void playerdown(void);
void* initbullet(void);
void* nextusablebullet(bullet_t *bullet);
void* nextbullet(bullet_t *bullet);
void freebullets(bullet_t *bullet);
void firebullet(bullet_t *bullet);
void inertia(bullet_t *bullet);
void bulletedgedetect(bullet_t *bullet);
void playerright(void);
void playerleft(void);
void playeredgedetect(void);
void* initenemies(void);
void* nextenemy(enemy_ll *enemy);
void* nextusableenemy(enemy_ll *enemy);
void freeenemies(enemy_ll *enemy);
void spawnenemy(enemy_ll *enemy);
void scoreadd(int score);
